spring:
  application:
    name: LibraSys
  #  profiles:
  #    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/libraSysDB
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    port: 465
    host: pro14.emailserver.vn
    username: quy2003@wuy.id.vn
    password: v9QcI2{ehK^)
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 616603233526-hu5q0l6h3ha9icuq5r3nbnagb1ji4rqf.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  signer-key: 0fCUCfplKd4o5fNUOBAkk1waUF7wbSHrPM5+MABZtLb13nzOw1yLekTVI2ChTbRs
  valid-duration: 86400 #in seconds 1days
  refreshable-duration: 604800 #in seconds 7days
server:
  port: 8009

logging:
  level:
    org:
      springframework:
        security: DEBUG


springdoc:
  api-docs:
    path: /api-docs
resilience4j.ratelimiter:
  instances:
    programClassUploadLimiter:
      limit-for-period: 1  # Số lượng yêu cầu được phép trong khoảng thời gian xác định
      limit-refresh-period: 1m  # Thời gian làm mới giới hạn (1 phút)
      timeout-duration: 0  # Thời gian tối đa phải chờ trước khi từ chối yêu cầu
cloudinary:
  cloud-name: dz9yzexh0
  api-key: 482653722794945
  api-secret: 23VTZBEf6rL-BBXVF3wOPqFWbas

